name: pet_talk
description: A Flutter implementation of PetTalk - Smart Pet Translator App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  
  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Network
  http: ^1.2.2
  dio: ^5.4.3+1
  
  # Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.1
  
  # Image Loading
  cached_network_image: ^3.3.1
  
  # Charts (for health data)
  fl_chart: ^0.68.0
  
  # Bluetooth
  flutter_blue_plus: ^1.32.12
  
  # Audio
  just_audio: ^0.9.38
  record: ^6.0.0
  
  # Camera
  camera: ^0.11.0+2
  image_picker: ^1.0.8
  
  # Utils
  intl: ^0.19.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  
  # Authentication
  google_sign_in: ^6.2.1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  sign_in_with_apple: ^6.1.1
  
  # Maps - 跨平台地图方案
  google_maps_flutter: ^2.6.1           # iOS使用Google Maps
  location: ^5.0.3                      # 通用定位服务
  geolocator: ^10.1.1                   # 通用地理位置服务
  
  # 百度地图SDK（仅Android使用，iOS会忽略）
  flutter_baidu_mapapi_base: ^3.8.1     # 百度地图基础库
  flutter_baidu_mapapi_map: ^3.8.1      # 百度地图显示组件
  flutter_baidu_mapapi_search: ^3.8.1   # 百度地图搜索和路径规划
  flutter_baidu_mapapi_utils: ^3.8.1    # 百度地图工具库
  flutter_bmflocation: ^3.3.0           # 百度定位服务
  
  # UI Components
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/activity/
    - assets/images/addpet/
    - assets/images/AI_function/
    - assets/images/health/
    - assets/images/info/
    - assets/images/login/
    - assets/images/profile/
    - assets/svg/
    - assets/svg/login/
    - assets/svg/module/
    - assets/svg/network/
    - assets/typeface/
  
  fonts:
    - family: PaaaWow
      fonts:
        - asset: assets/typeface/PaaaWow-Regular.ttf